### ISSUE TITLE
Duplicate Check

### ISSUE THREAD

**Issue by wakandaBP** [pondokcoder2020/PDC00001#15]
Fungsi _duplicate check_ pada api dapat ditulis sekali saja pada suatu _class_, agar setiap _class_ yg memerlukan tidak menulis ulang kembali kode dari fungsi _duplicate check_ (menghindari _boilerplate_).

**Comment by pondokcoder2020** [comment]
Fitur akan dipertimbangkan. Kemungkinan besar akan diimplementasikan pada Utility. Untuk sementara boleh dipakai di masing" class dulu.

**Comment by wakandaBP** [comment]
Sedikit tambahan, untuk fungsi Duplicate Check, agar mempertimbangkan pengecekan nilai duplikat tidak case sensitive. Sehingga saat pengecekan nilai, huruf besar dan kecil sama saja.
