### ISSUE TITLE
Item Resep racikan tidak muncul di menu verifikasi apotek

### ISSUE THREAD

**Issue by septia-anugrah** [pondokcoder2020/PDC00001#254]
![WhatsApp Image 2021-01-07 at 11 25 48 AM](https://user-images.githubusercontent.com/15723622/104189873-deac9780-544d-11eb-96bc-52b7215dbf7d.jpeg)

**Comment by pondokcoder2020** [comment]
Sudah fix di update #260 . Mohon pull dari master
