### ISSUE TITLE
Form dokter tidak bisa isi data nadi x/menit

### ISSUE THREAD

**Issue by septia-anugrah** [pondokcoder2020/PDC00001#255]
![WhatsApp Image 2021-01-07 at 11 26 29 AM](https://user-images.githubusercontent.com/15723622/104189982-00a61a00-544e-11eb-9fab-a148d680e688.jpeg)

**Comment by jonatansi** [comment]
Untuk input nadi dilakukan oleh perawat..
Dokter hanya dapat melihat hasil inputnya dari perawat

**Comment by septia-anugrah** [comment]
Berarti di disable saja inputTextnya bang

**Comment by pondokcoder2020** [comment]
![Screenshot_2021-01-13 SIMS Integrated v 2 0](https://user-images.githubusercontent.com/67011319/104347305-07f32380-5533-11eb-86d9-2632749d6b26.png)
