### ISSUE TITLE
Tampilkan penyedia di pencarian pemeriksaan laboratorium dan radiologi dokter

### ISSUE THREAD

**Issue by septia-anugrah** [pondokcoder2020/PDC00001#256]
![tampilkan kategori kontras radiologi](https://user-images.githubusercontent.com/15723622/104190366-95107c80-544e-11eb-9d42-72105432846f.png)
Disamping nama item pemeriksaan mohon tampilkan penyedia layanan. Misalnya Petala Bumi, Thamrin

![cari labor harusnya cari pemeriksaan](https://user-images.githubusercontent.com/15723622/104190485-c0936700-544e-11eb-8c21-7868fd7eba59.png)
Begitu juga dengan laboratorium

**Comment by pondokcoder2020** [comment]
Yang di bagian sini kemarin kami asumsi dokter tidak mau tau siapa penyelenggara tindakan penunjangnya bang. Ditentukan oleh orang masing" sh bang
Mention: @jonatansi , @ujo85

**Comment by septia-anugrah** [comment]
Untuk pembedanya bang. karena seperti THORAX AP itu ada petala bumi dan ibnu sina, dan namanya sama sama THORAX AP
