### ISSUE TITLE
Berikan centang all untuk parameter pemeriksaan laboratorium

### ISSUE THREAD

**Issue by septia-anugrah** [pondokcoder2020/PDC00001#257]
![centang all labor](https://user-images.githubusercontent.com/15723622/104190906-5929e700-544f-11eb-8041-1dd8dbcaf199.png)

**Comment by ujo85** [comment]
untuk ini tidak krusial jadi kita tunda untuk kedepanya

**Comment by septia-anugrah** [comment]
Oke bang. tapi ini berdasarkan keluhan dokter saat pelatihan bang

**Comment by ujo85** [comment]
kemarin kan sudah di buat untuk centang all kemudian di ubah menjadi centang satu, sekarang di ubah cetang all lagi. jadi kita kesampingkan dulu lagian ini ngak mengganggu alur kerja.
