### ISSUE TITLE
Error di form dokter

### ISSUE THREAD

**Issue by septia-anugrah** [pondokcoder2020/PDC00001#258]
![WhatsApp Image 2021-01-09 at 9 42 20 AM](https://user-images.githubusercontent.com/15723622/104191154-b756ca00-544f-11eb-9c36-39309f52a46d.jpeg)
![WhatsApp Image 2021-01-09 at 9 44 05 AM](https://user-images.githubusercontent.com/15723622/104191162-baea5100-544f-11eb-9e8d-5d491243977c.jpeg)

**Comment by pondokcoder2020** [comment]
Sudah done y bang karena konfigurasi tabel master_poli tadi ditambah fix conflict di local bang
