### ISSUE TITLE
Resep kosong masuk ke verifikasi resep

### ISSUE THREAD

**Issue by septia-anugrah** [pondokcoder2020/PDC00001#282]
Resep kosong masuk ke verifikasi resep saat dokter tidak memberikan resep untuk pasien dan menekan tombol selesai asesmen medis
![resep kosong](https://user-images.githubusercontent.com/15723622/106150798-484ad680-61ae-11eb-8289-793f7989ed3a.png)
![resep masuk verifiaksi](https://user-images.githubusercontent.com/15723622/106150809-4aad3080-61ae-11eb-9242-f3dab9a91b9f.png)

**Comment by pondokcoder2020** [comment]
Closes #283
