### ISSUE TITLE
Tagihan laboratorium pasien tidak muncul di kasir

### ISSUE THREAD

**Issue by septia-anugrah** [pondokcoder2020/PDC00001#283]
Nama pasien tidak muncul di list kasir untuk tagihan pembayaran laboratorium. Kondisi ini terjadi jika dokter hanya melakukan order pemeriksaan labor dan dokter tidak memberikan resep.
![tagihan pasien](https://user-images.githubusercontent.com/15723622/106151757-46354780-61af-11eb-9174-d7d88b48f230.png)

**Comment by pondokcoder2020** [comment]
Closes #293

**Comment by pondokcoder2020** [comment]
Closes #
