### ISSUE TITLE
Inputan hasil lab narasi

### ISSUE THREAD

**Issue by septia-anugrah** [pondokcoder2020/PDC00001#284]
Terdapat beberapa pemeriksaan lab yang tidak memiliki nilai hasil. seperti jaringan saraf terpi, yang hasil pemeriksaannya dalam bentuk kalimat naratif. 
![WhatsApp Image 2021-01-28 at 3 01 36 PM](https://user-images.githubusercontent.com/15723622/106152363-f014d400-61af-11eb-9482-74c2f1eb804e.jpeg)
contohnya seperti sputum yang nilai labnya kalimat narasi, jika nilai labnya pada gambar diatas tidak diisi maka pemeriksaannya tidak dapat dipilih
![WhatsApp Image 2021-01-28 at 3 03 21 PM](https://user-images.githubusercontent.com/15723622/106152649-47b33f80-61b0-11eb-927c-02821215a7f2.jpeg)

**Comment by pondokcoder2020** [comment]
Done
Closes #286
