### ISSUE TITLE
Custom Style

### ISSUE THREAD

**Issue by pondokcoder2020** [pondokcoder2020/PDC00001#346]
https://drive.google.com/file/d/1F0wLMpgSPrmqDObolkuVmx0tCvFajpio/view?usp=sharing 
https://drive.google.com/file/d/1vyFE319SZBHy3wqM4t7514B-tF6Nf5o3/view?usp=sharing

DELETE FROM kunjungan;
DELETE FROM antrian;
DELETE FROM antrian_nomor;
DELETE FROM asesmen;

DELETE FROM asesmen_rawat_tht;
DELETE FROM asesmen_medis_tht;

DELETE FROM resep;
DELETE FROM resep_detail;
DELETE FROM racikan;
DELETE FROM racikan_detail;
DELETE FROM resep_change_log;
DELETE FROM racikan_change_log;
DELETE FROM racikan_detail_change_log;

DELETE FROM igd;
DELETE FROM rawat_inap;
DELETE FROM rawat_inap_biaya_kamar;
DELETE FROM rawat_inap_riwayat_obat;
DELETE FROM rawat_inap_batch;
DELETE FROM rawat_inap_retur_obat;

DELETE FROM invoice;
DELETE FROM invoice_detail;
DELETE FROM invoice_payment;
DELETE FROM invoice_payment_detail;
DELETE FROM lab_order;
DELETE FROM lab_order_nilai;
DELETE FROM lab_order_detail;
DELETE FROM lab_order_document;
DELETE FROM rad_order;
DELETE FROM rad_order_detail;
DELETE FROM rad_order_document;
DELETE FROM inventori_mutasi;
DELETE FROM inventori_mutasi_detail;
DELETE FROM inventori_stok_log;

**Comment by pondokcoder2020** [comment]
git@github.com:pondokcoder2020/PDC00001.git

**Comment by theycantrevealus** [comment]
No response
