### ISSUE TITLE
Review zoom 1 Juli 2021

### ISSUE THREAD

**Issue by pondokcoder2020** [pondokcoder2020/PDC00001#358]
1. Tertekan next, antrian terlewat
2. Tombol selesai di dokter labor
3. Diagnosa pada verifikator apotek untuk kajian apotek terhadap resep
4. Enhance kecepatan load data resep
5. Pasien 1 kunjungan 2 antrian (BPJS dan umum)
6. Reset kunjungan setiap hari (jika tanggal kunjungan terakhir lebih lama dari hari ini maka akan dipulangkan dahulu otomatis agar setiap berganti hari pasien available)
7. Kajian resep dan cetak resep
8. Split otoritas dokter pada tindakan penunjang
9. Manajemen profile
10. Fix tampilan" (Logo dll)

Back Log case
1. Uji status ketersediaan batch pada verifikator

**Comment by theycantrevealus** [comment]
Close updated
