### ISSUE TITLE
Pasien baru rajal diarahkan ke form IGD

### ISSUE THREAD

**Issue by septia-anugrah** [pondokcoder2020/PDC00001#393]
Saat menambah data pasien baru Rajal pada form kunjungan yang muncul malah pilihan IGD 
![image](https://user-images.githubusercontent.com/15723622/129530590-bbc9ddd4-d51d-48d7-9274-3d017f41ebb4.png)

https://user-images.githubusercontent.com/15723622/129530614-cf75ada2-4c4f-4950-8c40-3a33dadf35bb.mp4

**Comment by theycantrevealus** [comment]
Ditambahkan pasien baru atas nama **MEGAWATI SOEKARNO PUTRI**
![Screenshot from 2021-08-16 15-14-23](https://user-images.githubusercontent.com/44671357/129532871-800ca231-e3b0-468e-9de4-863c86d8a03d.png)
Pasien terarahkan ke rajal seperti biasa
