### ISSUE TITLE
Karcis alignnya terlalu ke kiri

### ISSUE THREAD

**Issue by septia-anugrah** [pondokcoder2020/PDC00001#413]
![image](https://user-images.githubusercontent.com/15723622/130033582-56dffd83-2387-46ba-ad50-db1349695e53.png)

**Comment by Ryma88** [comment]
Mau d gunting pinggir nya,atau bisa d setup agak ke tengah

**Comment by septia-anugrah** [comment]
Setup ke tengah bang seperti karcis simrs_dev itu udah bagus bang. Kalau digunting satu satu karcisnya satu hari 100an bang. Lama pasien nunggu

**Comment by theycantrevealus** [comment]
Karcis sudah di set auto ke tengah
